steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function-tesla-get_location
  - --region=us-east4
  - --service_account_email=service-account-wyze-function@ensure-dev-zone.iam.gserviceaccount.com
  - --entry_point=tesla_get_location
  - --source=.
  - --trigger-http
  - --runtime=python39
options:
  logging: CLOUD_LOGGING_ONLY
