steps:
- name: python
  entrypoint: pip
  args: [ "install", "google-cloud-secret-manager", "--user" ]

- name: python
  entrypoint: python
  args: [ "secret_manager.py", download ,"src/settings.toml", tap_settings_files, $PROJECT_NUMBER ]
  id: load_settings_toml

- name: python
  entrypoint: python
  args: [ "secret_manager.py", download , "src/cache.json", tesla_cred, $PROJECT_NUMBER ]
  id: secret_manager
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function-tesla-get_location
  - --region=us-east4
#  - --service-account=service-account-wyze-function@ensure-dev-zone.iam.gserviceaccount.com
  - --service-account=tesla-sc-get-location@tesla-automation-397321.iam.gserviceaccount.com
  - --entry-point=tesla_get_location
  - --source=src
  - --trigger-http
  - --runtime=python39
  - --memory=256
  - --min-instances=1
  - --max-instances=2
  - --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
